### PR TITLE
fixed Exception and upgraded coverage dependency

### PR DESCRIPTION
**Pull request by denniskaselow**
I fixed the type of `hitmap` and updated the `coverage` dependency because `dart-coveralls` failed with the following Exception (probably since Dart 2.0.0-dev.64.1):

```
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, Map<int, int>>'
package:dart_coveralls/src/collect_lcov.dart 92:44  LcovCollector.getLcovInformation
===== asynchronous gap ===========================
dart:async                                          _AsyncAwaitCompleter.completeError
package:dart_coveralls/src/collect_lcov.dart        LcovCollector.getLcovInformation
===== asynchronous gap ===========================
dart:async                                          _asyncThenWrapperHelper
package:dart_coveralls/src/collect_lcov.dart        LcovCollector.getLcovInformation
package:dart_coveralls/src/cli_client.dart 40:22    CommandLineClient.getLcovResult
package:dart_coveralls/src/cli_client.dart 66:25    CommandLineClient.reportToCoveralls
```

### CODE REVIEW

**Comment by denniskaselow** [comment]
fixed by now

**Comment by pq** [comment]
Hi @denniskaselow.  Sorry I didn't see this!

You'll note that we're not actually out of the woods just yet as we're hanging at runtime (#84). I'm guessing this has to do with new async semantics but haven't had the time yet to look.

**Comment by denniskaselow** [comment]
And I closed this prematurely. I thought this issue because there was a new version with an upgraded dependency, but the type is still wrong.

**Comment by denniskaselow** [comment]
I'd guess the problem in #84 is also related to the type. They are not using the `--throw-on-error` flag so it just silently fails without printing the exception.

**Comment by pq** [comment]
@denniskaselow 

> I'd guess the problem in #84 is also related to the type

Maybe!  I was just suggesting async behavior because we've seen similar behavior elsewhere.  Anyway, this is great and we should land it -- though I admit I'm still seeing a hang with it patched in locally.  🤔  But maybe there are other similar failures getting silently suppressed?  Any more ideas welcome!  (I'll do some poking around in the meantime.)

Thanks!

**Pull request merged**
