### PR TITLE
Add option to report without calculating coverage

### PR DESCRIPTION
**Pull request by ekweible**
Until the coverage story/integration improves, there is not an easy way to run coverage on browser tests. This tool doesn't support browser tests, and as such that coverage cannot be easily reported. I've been working on a tool that enables coverage collection/formatting for any number of test files (vm or browser) over at https://github.com/ekweible/dart_codecov_generator. It can output the collective coverage in lcov format, but currently there's no way to report that coverage info directly.

This PR addresses this issue by adding a `calc` flag to the `report` task that can be negated, allowing the coverage calculation step to be skipped (assuming it's performed separately). Instead of expecting a test file in this scenario, an lcov file is expected. Usage looks like this:

```
pub run dart_coveralls report --no-calc coverage.lcov
```

### CODE REVIEW

**Comment by ekweible** [comment]
@Adracus

**Comment by Adracus** [comment]
The idea is pretty nice, but is there a way to integrate it more directly into dart-coveralls? It should be possible to directly specify a browser as a target for coverage data collection.

**Comment by ekweible** [comment]
I agree, but the dart_codecov_generator project is only meant to be a stopgap for dealing with coverage until the Dart team better integrates coverage into the test package, which I believe is currently waiting on better integration with observatory.

**Comment by eseidelGoogle** [comment]
Given how old this PR is this probably can be closed?  @nilsdoehring?

**Comment by nilsdoehring** [comment]
Closing due to age. Also, it seems that this functionality is covered by the ```upload``` command. If that's not the case, please file an issue.

**Pull request closed without merging**
